id: IEE3AFE94
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:36:57+00:00'
last_modified: '2022-06-08T05:46:57.119534+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W5743
  title: ལྷ་ཆོས་དང་མཐུན་པའི་གཏམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F47A:
      image_group_id: I5043
      title: ''
      total_pages: 82
      order: 1
      base_file: F47A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
